actor_lr: 0.0001
batch_size: 512
capacity: 10000
critic_lr: 0.0001
eps_end: 0.2
eps_last_episode: 500
eps_start: 1
gamma: 0.99
hidden_size: 256
loss_fn: !!python/name:torch.nn.functional.smooth_l1_loss ''
optim: !!python/name:torch.optim.adamw.AdamW ''
samples_per_epoch: 20
save_location: ./DDPG_ant_brax/
tau: 0.01
