a_end: 0.0
a_last_episode: 100
a_start: 0.5
b_end: 0
b_last_episode: 100
b_start: 0.4
batch_size: 32
capacity: 100000
gamma: 0.99
hidden_size: 128
loss_fn: !!python/name:torch.nn.functional.smooth_l1_loss ''
lr: 0.001
max_steps: 1000
optim: !!python/name:torch.optim.adamw.AdamW ''
policy: !!python/name:__main__.greedy ''
samples_per_epoch: 10000
save_location: ./Noisy_DoubleDuelingDQN_prioritized_results/
sigma: 0.5
sync_rate: 10
